name: ep_fv2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+7

# 20210818 1.0.0+1 First Release
# 20210904 1.0.1+2 Extend Api connection timeout to 30 seconds
# 20210913 1.0.2+3 Validate gender when enter weight, visit list able to show even got no location data
# 20211026 1.0.3+4 add schedule day field to visit table, add A gender to weight, pasgar criteria
# 20211129 1.0.4+5 add avg weight at bottom of weight summary
# 20211129 1.0.5+6 add summary avg weight
# 20211130 1.0.6+7 edit summary avg weight display text

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  package_info: ^2.0.2
  url_launcher: ^6.0.9
  intl: ^0.17.0
  uuid: ^3.0.4
  collection: ^1.15.0
  image_picker: ^0.8.3
  flutter_image_compress: ^1.1.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0

  moor: ^4.4.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  path: ^1.8.0

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.4.1
  build_runner: ^2.1.1

flutter:
  uses-material-design: true


